//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Casgem_Portfolio.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblReference
    {
        public int ID { get; set; }
        public string ReferenceName { get; set; }
        public string ReferenceNumber { get; set; }
        public string ReferenceMail { get; set; }
        public string ReferenceImageUrl { get; set; }
    }
}
